-- Update existing projects with more detailed descriptions and gallery images

UPDATE projects SET 
  description = E'Our client, a fast-growing e-commerce platform with over 500,000 monthly visitors, was struggling with customer engagement and conversion rates. Traditional chatbots were failing to understand nuanced customer queries, leading to frustration and abandoned carts.\n\nWe developed an intelligent shopping assistant powered by advanced natural language processing and machine learning algorithms. The AI agent can:\n\n• Understand complex product queries and provide personalized recommendations\n• Learn from customer interactions to improve over time\n• Handle multiple languages and regional preferences\n• Integrate seamlessly with existing inventory and CRM systems\n• Provide real-time product availability and pricing information\n\nResults:\n• 40% increase in customer engagement metrics\n• 25% boost in overall sales conversion\n• 60% reduction in cart abandonment rate\n• 85% customer satisfaction rating for AI interactions\n• ROI achieved within 3 months of deployment',
  gallery = '["https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1080&q=80", "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1080&q=80", "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1080&q=80", "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1080&q=80"]'::jsonb
WHERE title = 'E-commerce AI Assistant';

UPDATE projects SET 
  description = E'A leading digital marketing agency was spending countless hours creating custom content for their diverse client portfolio. They needed to scale content production while maintaining quality and brand consistency across 20+ different client voices.\n\nWe built an end-to-end automated content generation pipeline that:\n\n• Analyzes brand guidelines and previous content to learn unique voices\n• Generates SEO-optimized articles, blog posts, and social media content\n• Integrates with content management systems for seamless publishing\n• Includes automated fact-checking and plagiarism detection\n• Provides A/B testing capabilities for headline optimization\n• Maintains human oversight through smart review workflows\n\nKey Features:\n• Multi-platform content adaptation (blog, social media, email)\n• Dynamic SEO keyword integration\n• Tone and style customization per brand\n• Automated image selection and optimization\n• Performance analytics and continuous improvement\n\nImpact:\n• 10x increase in content output (from 10 to 100+ pieces weekly)\n• 70% reduction in content production costs\n• Maintained 95% approval rate from clients\n• Improved average SEO rankings by 35%',
  gallery = '["https://images.unsplash.com/photo-1552664730-d307ca884978?w=1080&q=80", "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1080&q=80", "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1080&q=80"]'::jsonb
WHERE title = 'Content Generation Pipeline';

UPDATE projects SET 
  description = E'A global SaaS company was drowning in customer support tickets, with response times averaging 6-8 hours. Their 50-person support team couldn''t keep up with growing demand, and customer satisfaction was declining.\n\nWe developed a sophisticated multilingual customer service bot that:\n\n• Handles tier-1 support inquiries across 12 languages\n• Integrates with knowledge base and product documentation\n• Escalates complex issues to human agents with full context\n• Learns from resolved tickets to expand capabilities\n• Provides 24/7 instant responses\n• Maintains conversation context across multiple interactions\n\nTechnical Capabilities:\n• Natural language understanding in 12 languages\n• Sentiment analysis for escalation prioritization\n• Integration with ticketing system, CRM, and product databases\n• Automated ticket categorization and routing\n• Real-time translation for agent handoffs\n• Continuous learning from agent corrections\n\nBusiness Impact:\n• 80% of inquiries resolved automatically\n• Response time reduced from hours to seconds\n• Support team refocused on complex, high-value issues\n• Customer satisfaction score increased from 3.2 to 4.6/5\n• Support costs reduced by 45%\n• Enabled 24/7 global support coverage',
  gallery = '["https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1080&q=80", "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=1080&q=80", "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1080&q=80", "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1080&q=80", "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1080&q=80"]'::jsonb
WHERE title = 'Customer Service Bot';

UPDATE projects SET 
  description = E'A B2B technology company was struggling to maintain consistent social media presence across LinkedIn, Twitter, Facebook, and Instagram. Their small marketing team of 3 people couldn''t keep up with the demand for fresh, engaging content on multiple platforms.\n\nWe created an AI-powered social media automation system that:\n\n• Generates platform-specific content optimized for each channel\n• Schedules posts at optimal times based on audience engagement data\n• Automatically repurposes long-form content into social media posts\n• Creates relevant hashtag suggestions and trending topic integration\n• Monitors engagement and adjusts strategy in real-time\n• Generates performance reports and actionable insights\n\nPlatform Features:\n• Multi-platform content adaptation and formatting\n• Intelligent scheduling based on audience behavior patterns\n• Automated image generation and optimization\n• Brand voice consistency across all channels\n• Competitor analysis and trend identification\n• A/B testing for post optimization\n• Crisis detection and alert system\n\nResults:\n• 5x increase in social media posting frequency\n• 120% growth in overall engagement rates\n• 85% reduction in time spent on social media management\n• Consistent brand presence across all platforms\n• 40% increase in website traffic from social channels\n• Marketing team refocused on strategy and creative work',
  gallery = '["https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1080&q=80", "https://images.unsplash.com/photo-1579869847557-1f67382cc158?w=1080&q=80", "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=1080&q=80"]'::jsonb
WHERE title = 'Social Media Automation';

-- Add new diverse projects to showcase different capabilities

INSERT INTO projects (title, description, cover_image_url, gallery, external_url, is_featured, sort_order) VALUES 

('Healthcare Document Processing', 
E'A large healthcare network was processing thousands of patient records, insurance claims, and medical documents daily. Manual data entry was slow, error-prone, and consuming significant staff resources.\n\nWe implemented an AI-powered document processing system that:\n\n• Automatically extracts data from medical records, insurance forms, and referrals\n• Validates information against existing patient databases\n• Flags inconsistencies and potential errors for review\n• Routes documents to appropriate departments automatically\n• Ensures HIPAA compliance throughout the process\n• Integrates with existing EMR systems\n\nTechnology Stack:\n• Computer vision for document scanning and OCR\n• Natural language processing for medical terminology\n• Machine learning for data validation\n• Secure, encrypted data handling\n• Audit trails for compliance\n\nOutcomes:\n• 90% reduction in manual data entry time\n• 75% decrease in processing errors\n• 100% HIPAA compliance maintained\n• $500K annual cost savings\n• Staff redeployed to patient care activities\n• Average processing time reduced from 48 hours to 4 hours',
'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1080&q=80',
'["https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=1080&q=80", "https://images.unsplash.com/photo-1504813184591-01572f98c85f?w=1080&q=80", "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=1080&q=80"]'::jsonb,
null,
false,
5),

('Financial Fraud Detection System',
E'A fintech startup needed to protect their rapidly growing user base from fraudulent transactions while minimizing false positives that would frustrate legitimate customers.\n\nWe developed a real-time fraud detection system powered by machine learning that:\n\n• Analyzes transaction patterns in real-time\n• Identifies anomalies and suspicious behavior\n• Adapts to new fraud techniques automatically\n• Provides risk scores for each transaction\n• Minimizes false positives through intelligent scoring\n• Integrates with existing payment infrastructure\n\nKey Capabilities:\n• Real-time transaction analysis (< 100ms response time)\n• Behavioral biometrics and device fingerprinting\n• Network analysis to identify fraud rings\n• Continuous learning from confirmed fraud cases\n• Customizable risk thresholds per transaction type\n• Detailed audit logs and reporting\n\nBusiness Results:\n• 95% fraud detection rate\n• 60% reduction in false positives\n• $2M+ in prevented fraudulent transactions annually\n• Processing time under 100ms for seamless UX\n• Enabled expansion into higher-risk markets\n• Regulatory compliance maintained',
'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1080&q=80',
'["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1080&q=80", "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1080&q=80", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1080&q=80", "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1080&q=80"]'::jsonb,
null,
true,
6),

('Supply Chain Optimization Platform',
E'A manufacturing company with complex global supply chains was facing frequent delays, inventory issues, and inefficient resource allocation. Traditional planning methods couldn''t handle the complexity.\n\nWe built an AI-powered supply chain optimization platform that:\n\n• Predicts demand patterns across multiple product lines\n• Optimizes inventory levels at each warehouse location\n• Identifies potential supply chain disruptions before they occur\n• Recommends optimal shipping routes and methods\n• Automates reordering based on predictive analytics\n• Provides real-time visibility across the entire supply chain\n\nAdvanced Features:\n• Multi-variable demand forecasting\n• Weather and events impact analysis\n• Supplier reliability scoring\n• Dynamic route optimization\n• Inventory optimization algorithms\n• What-if scenario modeling\n• Integration with ERP, WMS, and TMS systems\n\nMeasurable Impact:\n• 30% reduction in inventory carrying costs\n• 45% decrease in stockout incidents\n• 25% improvement in on-time delivery rates\n• $1.5M annual savings in transportation costs\n• 40% faster response to supply chain disruptions\n• Improved supplier relationship management',
'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1080&q=80',
'["https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=1080&q=80", "https://images.unsplash.com/photo-1553413077-190dd305871c?w=1080&q=80", "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1080&q=80"]'::jsonb,
null,
false,
7),

('Recruitment AI Screening Tool',
E'A fast-growing tech company was receiving 10,000+ applications monthly for various roles. Their HR team of 8 people was overwhelmed, and qualified candidates were slipping through the cracks or waiting weeks for responses.\n\nWe developed an AI-powered recruitment screening system that:\n\n• Analyzes resumes and applications automatically\n• Matches candidates to job requirements intelligently\n• Eliminates unconscious bias in initial screening\n• Conducts preliminary interviews via chat\n• Schedules qualified candidates for human interviews\n• Provides detailed candidate insights to recruiters\n\nEthical AI Features:\n• Bias detection and mitigation algorithms\n• Transparent scoring methodology\n• Compliance with employment regulations\n• Candidate privacy protection\n• Human oversight at critical decision points\n• Continuous auditing for fairness\n\nRecruitment Outcomes:\n• 95% reduction in initial screening time\n• 70% increase in qualified candidate identification\n• Time-to-hire reduced from 45 to 18 days\n• 40% improvement in candidate diversity\n• Enhanced candidate experience with faster responses\n• HR team refocused on strategic talent initiatives\n• 85% recruiter satisfaction with AI recommendations',
'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1080&q=80',
'["https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1080&q=80", "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1080&q=80", "https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=1080&q=80", "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1080&q=80"]'::jsonb,
null,
true,
8);
